# Generated by Django 3.1.4 on 2021-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
