# Generated by Django 3.1.4 on 2021-06-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_auto_20210619_0924"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="ecological_ranking",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="economic_ranking",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="social_ranking",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="technical_ranking",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
