# Generated by Django 3.1.4 on 2021-06-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_auto_20210622_1704"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="description",
            new_name="overview",
        ),
        migrations.AddField(
            model_name="location",
            name="economic_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="location",
            name="efficiency_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="location",
            name="environmental_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="location",
            name="social_description",
            field=models.TextField(blank=True),
        ),
    ]
